{% set name = "bitstring" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a391db8828ac4485dd5ce72c80b27ebac3e7b989631359959e310cd9729723b2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - bitstring

about:
  home: http://scott-griffiths.github.io/bitstring
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple construction, analysis and modification of binary data.
  doc_url: https://bitstring.readthedocs.io
  dev_url: https://github.com/scott-griffiths/bitstring

extra:
  recipe-maintainers:
    - m-rossi
