{% set name = "bitstring" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81800bc4e00b6508716adbae648e741256355c8dfd19541f76482fb89bee0313

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61
  run:
    - bitarray >=3.0.0,<3.1
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - bitstring

about:
  home: http://scott-griffiths.github.io/bitstring
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple construction, analysis and modification of binary data.
  doc_url: https://bitstring.readthedocs.io
  dev_url: https://github.com/scott-griffiths/bitstring

extra:
  recipe-maintainers:
    - m-rossi
