{% set name = "bitstring" %}
{% set version = "4.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a08bc09d3857216d4c0f412a1611056f1cc2b64fd254fb1e8a0afba7cfa1a95a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61
  run:
    - bitarray >=3.0.0,<4.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - bitstring

about:
  home: http://scott-griffiths.github.io/bitstring
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple construction, analysis and modification of binary data.
  doc_url: https://bitstring.readthedocs.io
  dev_url: https://github.com/scott-griffiths/bitstring

extra:
  recipe-maintainers:
    - m-rossi
