{% set name = "bitstring" %}
{% set version = "4.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b40b01d911eebaea6efff40d826580806dced5e04b9d3cbad6aebf9422f4b643

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - bitarray >=2.9.0,<3
    - python >=3.8

test:
  imports:
    - bitstring

about:
  home: http://scott-griffiths.github.io/bitstring
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple construction, analysis and modification of binary data.
  doc_url: https://bitstring.readthedocs.io
  dev_url: https://github.com/scott-griffiths/bitstring

extra:
  recipe-maintainers:
    - m-rossi
